-- =============================================================
-- Fix 1: Quiz questions - only app owner can manage
-- =============================================================
DROP POLICY IF EXISTS "Authenticated can manage quiz questions" ON public.quiz_questions;
CREATE POLICY "Admins can manage quiz questions" ON public.quiz_questions
  FOR ALL TO authenticated
  USING (
    EXISTS (SELECT 1 FROM apps WHERE apps.id = quiz_questions.app_id AND apps.user_id = auth.uid() LIMIT 1)
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM apps WHERE apps.id = quiz_questions.app_id AND apps.user_id = auth.uid() LIMIT 1)
  );

-- =============================================================
-- Fix 2: App clients - only app owner can read
-- =============================================================
DROP POLICY IF EXISTS "Admins can view all clients" ON public.app_clients;
CREATE POLICY "App owner can view clients" ON public.app_clients
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM apps WHERE apps.user_id = auth.uid() LIMIT 1
    )
  );

-- =============================================================
-- Fix 3: Storage - remove public listing on app-assets
-- Only authenticated (admin) can see files in app-assets
-- Clients use signed URLs (generated by edge function)
-- =============================================================
DROP POLICY IF EXISTS "Anyone can read app-assets" ON storage.objects;
DROP POLICY IF EXISTS "Public read access" ON storage.objects;

-- Admin can manage own files
CREATE POLICY "Admin upload own files" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'app-assets' AND (storage.foldername(name))[1] = auth.uid()::text);

CREATE POLICY "Admin read own files" ON storage.objects
  FOR SELECT TO authenticated
  USING (bucket_id = 'app-assets' AND (storage.foldername(name))[1] = auth.uid()::text);

CREATE POLICY "Admin update own files" ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'app-assets' AND (storage.foldername(name))[1] = auth.uid()::text);

CREATE POLICY "Admin delete own files" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'app-assets' AND (storage.foldername(name))[1] = auth.uid()::text);
